##Import Libraries

In [7]:
# ============================================================
# TCGA-BRCA Clinical Data Preprocessing
# Master's Thesis
# ============================================================

import os
import warnings
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 150)

print("="*70)
print("TCGA-BRCA CLINICAL PREPROCESSING")
print("="*70)

======================================================================
TCGA-BRCA CLINICAL PREPROCESSING
======================================================================

##Mount Google Drive

In [8]:
# ============================================================
# Mount Google Drive
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

##Define Paths & Load Dataset

In [9]:
# ============================================================
# Load Clinical Dataset
# ============================================================

DATA_DIR = "/content/drive/MyDrive/BreastCanser-DataSet"

CLINICAL_FILE = os.path.join(
    DATA_DIR,
    "Human__TCGA_BRCA__MS__Clinical__Clinical__01_28_2016__BI__Clinical__Firehose.tsv"
)

clinical_raw = pd.read_csv(
    CLINICAL_FILE,
    sep="\t"
)

print("="*70)
print("DATA LOADED SUCCESSFULLY")
print("="*70)

print(f"Dataset shape: {clinical_raw.shape}")

======================================================================
DATA LOADED SUCCESSFULLY
======================================================================
Dataset shape: (20, 1098)

##Dataset Inspection

In [10]:
# ============================================================
# Dataset Inspection
# ============================================================

print("="*70)
print("FIRST FIVE ROWS")
print("="*70)

display(clinical_raw.head())

print("\nColumn names:")
print(clinical_raw.columns.tolist()[:10])

print("\n")

print("="*70)
print("DATASET SUMMARY")
print("="*70)

print(f"Clinical variables (rows): {clinical_raw.shape[0]}")
print(f"Patients (columns):        {clinical_raw.shape[1]-1}")

print("\nFeature column:")
print(clinical_raw.columns[0])

print("\nExample patient IDs:")
print(clinical_raw.columns[1:11].tolist())

print("\nMissing values:")
print(clinical_raw.isna().sum().sum())

print("\nDuplicate clinical variables:")
print(clinical_raw.iloc[:,0].duplicated().sum())

print("\nDuplicate patient columns:")
print(clinical_raw.columns[1:].duplicated().sum())

======================================================================
FIRST FIVE ROWS
======================================================================

,attrib_name,TCGA.5L.AAT0,TCGA.5L.AAT1,TCGA.A1.A0SP,TCGA.A2.A04V,TCGA.A2.A04Y,TCGA.A2.A0CQ,TCGA.A2.A1G4,TCGA.A2.A25A,TCGA.A7.A0CD,TCGA.A7.A13G,TCGA.A7.A26E,TCGA.A7.A26F,TCGA.A7.A26H,TCGA.A7.A26I,TCGA.A7.A2KD,TCGA.A7.A3J1,TCGA.A7.A426,TCGA.A7.A5ZX,TCGA.A8.A06T,TCGA.A8.A06U,TCGA.A8.A07E,TCGA.A8.A084,TCGA.A8.A08F,TCGA.A8.A08S,TCGA.A8.A091,TCGA.A8.A093,TCGA.A8.A09C,TCGA.A8.A09E,TCGA.A8.A09I,TCGA.A8.A09K,TCGA.AC.A3W5,TCGA.AC.A3W6,TCGA.AC.A5EI,TCGA.AC.A5XS,TCGA.AC.A62X,TCGA.AO.A0JI,TCGA.AO.A1KT,TCGA.AQ.A0Y5,TCGA.AQ.A54N,TCGA.AQ.A54O,TCGA.AQ.A7U7,TCGA.AR.A1AM,TCGA.AR.A1AR,TCGA.AR.A2LL,TCGA.AR.A2LR,TCGA.AR.A5QM,TCGA.B6.A0I8,TCGA.BH.A0B6,TCGA.BH.A0DO,TCGA.BH.A0EA,TCGA.BH.A18H,TCGA.BH.A1F5,TCGA.BH.A8FY,TCGA.C8.A1HL,TCGA.D8.A146,TCGA.E2.A158,TCGA.E2.A15O,TCGA.E2.A1BC,TCGA.E2.A1L8,TCGA.E2.A1LG,TCGA.E2.A2P5,TCGA.E2.A572,TCGA.EW.A1J5,TCGA.EW.A1P3,TCGA.GM.A2DD,TCGA.GM.A2DO,TCGA.LD.A74U,TCGA.LL.A440,TCGA.LL.A442,TCGA.LL.A50Y,TCGA.LL.A5YP,TCGA.LL.A740,TCGA.OL.A5RU,TCGA.S3.AA12,TCGA.S3.AA17,TCGA.W8.A86G,TCGA.WT.AB41,TCGA.Z7.A8R5,TCGA.3C.AAAU,TCGA.3C.AALI,TCGA.3C.AALJ,TCGA.3C.AALK,TCGA.4H.AAAK,TCGA.5T.A9QA,TCGA.A1.A0SB,TCGA.A1.A0SD,TCGA.A1.A0SE,TCGA.A1.A0SF,TCGA.A1.A0SG,TCGA.A1.A0SH,TCGA.A1.A0SI,TCGA.A1.A0SJ,TCGA.A1.A0SK,TCGA.A1.A0SM,TCGA.A1.A0SN,TCGA.A1.A0SO,TCGA.A1.A0SQ,TCGA.A2.A04N,TCGA.A2.A04P,TCGA.A2.A04Q,TCGA.A2.A04R,TCGA.A2.A04T,TCGA.A2.A04U,TCGA.A2.A04W,TCGA.A2.A04X,TCGA.A2.A0CK,TCGA.A2.A0CL,TCGA.A2.A0CM,TCGA.A2.A0CO,TCGA.A2.A0CP,TCGA.A2.A0CR,TCGA.A2.A0CS,TCGA.A2.A0CT,TCGA.A2.A0CU,TCGA.A2.A0CV,TCGA.A2.A0CW,TCGA.A2.A0CX,TCGA.A2.A0CY,TCGA.A2.A0CZ,TCGA.A2.A0D0,TCGA.A2.A0D1,TCGA.A2.A0D2,TCGA.A2.A0D3,TCGA.A2.A0D4,TCGA.A2.A0EM,TCGA.A2.A0EN,TCGA.A2.A0EO,TCGA.A2.A0EP,TCGA.A2.A0EQ,TCGA.A2.A0ER,TCGA.A2.A0ES,TCGA.A2.A0ET,TCGA.A2.A0EU,TCGA.A2.A0EV,TCGA.A2.A0EW,TCGA.A2.A0EX,TCGA.A2.A0EY,TCGA.A2.A0ST,TCGA.A2.A0SU,TCGA.A2.A0SV,TCGA.A2.A0SW,TCGA.A2.A0SX,TCGA.A2.A0SY,TCGA.A2.A0T0,TCGA.A2.A0T1,TCGA.A2.A0T2,TCGA.A2.A0T3,TCGA.A2.A0T4,TCGA.A2.A0T5,TCGA.A2.A0T6,TCGA.A2.A0T7,TCGA.A2.A0YC,TCGA.A2.A0YD,TCGA.A2.A0YE,TCGA.A2.A0YF,TCGA.A2.A0YG,TCGA.A2.A0YH,TCGA.A2.A0YI,TCGA.A2.A0YJ,TCGA.A2.A0YK,TCGA.A2.A0YL,TCGA.A2.A0YM,TCGA.A2.A0YT,TCGA.A2.A1FV,TCGA.A2.A1FW,TCGA.A2.A1FX,TCGA.A2.A1FZ,TCGA.A2.A1G0,TCGA.A2.A1G1,TCGA.A2.A1G6,TCGA.A2.A259,TCGA.A2.A25B,TCGA.A2.A25C,TCGA.A2.A25D,TCGA.A2.A25E,TCGA.A2.A25F,TCGA.A2.A3KC,TCGA.A2.A3KD,TCGA.A2.A3XS,TCGA.A2.A3XT,TCGA.A2.A3XU,TCGA.A2.A3XV,TCGA.A2.A3XW,TCGA.A2.A3XX,TCGA.A2.A3XY,TCGA.A2.A3XZ,TCGA.A2.A3Y0,TCGA.A2.A4RW,TCGA.A2.A4RX,TCGA.A2.A4RY,TCGA.A2.A4S0,TCGA.A2.A4S1,TCGA.A2.A4S2,TCGA.A2.A4S3,TCGA.A7.A0CE,TCGA.A7.A0CG,TCGA.A7.A0CH,TCGA.A7.A0CJ,TCGA.A7.A0D9,TCGA.A7.A0DA,TCGA.A7.A0DB,TCGA.A7.A0DC,TCGA.A7.A13D,TCGA.A7.A13E,TCGA.A7.A13F,TCGA.A7.A13H,TCGA.A7.A26G,TCGA.A7.A26J,TCGA.A7.A3IY,TCGA.A7.A3IZ,TCGA.A7.A3J0,TCGA.A7.A3RF,TCGA.A7.A425,TCGA.A7.A4SA,TCGA.A7.A4SB,TCGA.A7.A4SC,TCGA.A7.A4SD,TCGA.A7.A4SE,TCGA.A7.A4SF,TCGA.A7.A56D,TCGA.A7.A5ZV,TCGA.A7.A5ZW,TCGA.A7.A6VV,TCGA.A7.A6VW,TCGA.A7.A6VX,TCGA.A7.A6VY,TCGA.A8.A06N,TCGA.A8.A06O,TCGA.A8.A06P,TCGA.A8.A06Q,TCGA.A8.A06R,TCGA.A8.A06X,TCGA.A8.A06Y,TCGA.A8.A06Z,TCGA.A8.A075,TCGA.A8.A076,TCGA.A8.A079,TCGA.A8.A07B,TCGA.A8.A07C,TCGA.A8.A07F,TCGA.A8.A07G,TCGA.A8.A07I,TCGA.A8.A07J,TCGA.A8.A07L,TCGA.A8.A07O,TCGA.A8.A07P,TCGA.A8.A07R,TCGA.A8.A07S,TCGA.A8.A07U,TCGA.A8.A07W,TCGA.A8.A07Z,TCGA.A8.A081,TCGA.A8.A082,TCGA.A8.A083,TCGA.A8.A085,TCGA.A8.A086,TCGA.A8.A08A,TCGA.A8.A08B,TCGA.A8.A08C,TCGA.A8.A08G,TCGA.A8.A08H,TCGA.A8.A08I,TCGA.A8.A08J,TCGA.A8.A08L,TCGA.A8.A08O,TCGA.A8.A08P,TCGA.A8.A08R,TCGA.A8.A08T,TCGA.A8.A08X,TCGA.A8.A08Z,TCGA.A8.A090,TCGA.A8.A092,TCGA.A8.A094,TCGA.A8.A095,TCGA.A8.A096,TCGA.A8.A097,TCGA.A8.A099,TCGA.A8.A09A,TCGA.A8.A09B,TCGA.A8.A09D,TCGA.A8.A09G,TCGA.A8.A09M,TCGA.A8.A09N,TCGA.A8.A09Q,TCGA.A8.A09R,TCGA.A8.A09T,TCGA.A8.A09V,TCGA.A8.A09W,TCGA.A8.A09X,TCGA.A8.A09Z,TCGA.A8.A0A1,TCGA.A8.A0A2,TCGA.A8.A0A4,TCGA.A8.A0A6,TCGA.A8.A0A7,TCGA.A8.A0A9,TCGA.A8.A0AB,TCGA.A8.A0AD,TCGA.AC.A23C,TCGA.AC.A23E,TCGA.AC.A23G,TCGA.AC.A23H,TCGA.AC.A2B8,TCGA.AC.A2BK,TCGA.AC.A2BM,TCGA.AC.A2FB,TCGA.AC.A2FE,TCGA.AC.A2FF,TCGA.AC.A2FG,TCGA.AC.A2FK,TCGA.AC.A2FM,TCGA.AC.A2FO,TCGA.AC.A2QH,TCGA.AC.A2QI,TCGA.AC.A2QJ,TCGA.AC.A3BB,TCGA.AC.A3EH,TCGA.AC.A3HN,TCGA.AC.A3OD,TCGA.AC.A3QP,TCGA.AC.A3QQ,TCGA.AC.A3TM,TCGA.AC.A3TN,TCGA.AC.A3W7,TCGA.AC.A3YI,TCGA.AC.A3YJ,TCGA.AC.A4ZE,TCGA.AC.A5EH,TCGA.AC.A5XU,TCGA.AC.A62V,TCGA.AC.A62Y,TCGA.AC.A6IV,TCGA.AC.A6IW,TCGA.AC.A6IX,TCGA.AC.A6NO,TCGA.AC.A7VB,TCGA.AC.A7VC,TCGA.AC.A8OP,TCGA.AC.A8OQ,TCGA.AC.A8OR,TCGA.AC.A8OS,TCGA.AN.A03X,TCGA.AN.A03Y,TCGA.AN.A041,TCGA.AN.A046,TCGA.AN.A049,TCGA.AN.A04A,TCGA.AN.A04C,TCGA.AN.A04D,TCGA.AN.A0AJ,TCGA.AN.A0AK,TCGA.AN.A0AL,TCGA.AN.A0AM,TCGA.AN.A0AR,TCGA.AN.A0AS,TCGA.AN.A0AT,TCGA.AN.A0FD,TCGA.AN.A0FF,TCGA.AN.A0FJ,TCGA.AN.A0FK,TCGA.AN.A0FL,TCGA.AN.A0FN,TCGA.AN.A0FS,TCGA.AN.A0FT,TCGA.AN.A0FV,TCGA.AN.A0FW,TCGA.AN.A0FX,TCGA.AN.A0FY,TCGA.AN.A0FZ,TCGA.AN.A0G0,TCGA.AN.A0XL,TCGA.AN.A0XN,TCGA.AN.A0XO,TCGA.AN.A0XP,TCGA.AN.A0XR,TCGA.AN.A0XS,TCGA.AN.A0XT,TCGA.AN.A0XU,TCGA.AN.A0XV,TCGA.AN.A0XW,TCGA.AO.A03L,TCGA.AO.A03M,TCGA.AO.A03N,TCGA.AO.A03O,TCGA.AO.A03P,TCGA.AO.A03R,TCGA.AO.A03T,TCGA.AO.A03U,TCGA.AO.A03V,TCGA.AO.A0J2,TCGA.AO.A0J3,TCGA.AO.A0J4,TCGA.AO.A0J5,TCGA.AO.A0J6,TCGA.AO.A0J7,TCGA.AO.A0J8,TCGA.AO.A0J9,TCGA.AO.A0JA,TCGA.AO.A0JB,TCGA.AO.A0JC,TCGA.AO.A0JD,TCGA.AO.A0JE,TCGA.AO.A0JF,TCGA.AO.A0JG,TCGA.AO.A0JJ,TCGA.AO.A0JL,TCGA.AO.A0JM,TCGA.AO.A124,TCGA.AO.A125,TCGA.AO.A126,TCGA.AO.A128,TCGA.AO.A129,TCGA.AO.A12A,TCGA.AO.A12B,TCGA.AO.A12C,TCGA.AO.A12D,TCGA.AO.A12E,TCGA.AO.A12F,TCGA.AO.A12G,TCGA.AO.A12H,TCGA.AO.A1KO,TCGA.AO.A1KP,TCGA.AO.A1KQ,TCGA.AO.A1KR,TCGA.AO.A1KS,TCGA.AQ.A04H,TCGA.AQ.A04J,TCGA.AQ.A04L,TCGA.AQ.A1H2,TCGA.AQ.A1H3,TCGA.AR.A0TP,TCGA.AR.A0TQ,TCGA.AR.A0TR,TCGA.AR.A0TS,TCGA.AR.A0TT,TCGA.AR.A0TU,TCGA.AR.A0TV,TCGA.AR.A0TW,TCGA.AR.A0TX,TCGA.AR.A0TY,TCGA.AR.A0TZ,TCGA.AR.A0U0,TCGA.AR.A0U1,TCGA.AR.A0U2,TCGA.AR.A0U3,TCGA.AR.A0U4,TCGA.AR.A1AH,TCGA.AR.A1AI,TCGA.AR.A1AJ,TCGA.AR.A1AK,TCGA.AR.A1AL,TCGA.AR.A1AN,TCGA.AR.A1AO,TCGA.AR.A1AP,TCGA.AR.A1AQ,TCGA.AR.A1AS,TCGA.AR.A1AT,TCGA.AR.A1AU,TCGA.AR.A1AV,TCGA.AR.A1AW,TCGA.AR.A1AX,TCGA.AR.A1AY,TCGA.AR.A24H,TCGA.AR.A24K,TCGA.AR.A24L,TCGA.AR.A24M,TCGA.AR.A24N,TCGA.AR.A24O,TCGA.AR.A24P,TCGA.AR.A24Q,TCGA.AR.A24R,TCGA.AR.A24S,TCGA.AR.A24T,TCGA.AR.A24U,TCGA.AR.A24V,TCGA.AR.A24W,TCGA.AR.A24X,TCGA.AR.A24Z,TCGA.AR.A250,TCGA.AR.A251,TCGA.AR.A252,TCGA.AR.A254,TCGA.AR.A255,TCGA.AR.A256,TCGA.AR.A2LE,TCGA.AR.A2LH,TCGA.AR.A2LJ,TCGA.AR.A2LK,TCGA.AR.A2LM,TCGA.AR.A2LN,TCGA.AR.A2LO,TCGA.AR.A2LQ,TCGA.AR.A5QN,TCGA.AR.A5QP,TCGA.AR.A5QQ,TCGA.B6.A0I1,TCGA.B6.A0I2,TCGA.B6.A0I5,TCGA.B6.A0I6,TCGA.B6.A0I9,TCGA.B6.A0IA,TCGA.B6.A0IB,TCGA.B6.A0IC,TCGA.B6.A0IE,TCGA.B6.A0IG,TCGA.B6.A0IH,TCGA.B6.A0IJ,TCGA.B6.A0IK,TCGA.B6.A0IM,TCGA.B6.A0IN,TCGA.B6.A0IO,TCGA.B6.A0IP,TCGA.B6.A0IQ,TCGA.B6.A0RE,TCGA.B6.A0RG,TCGA.B6.A0RH,TCGA.B6.A0RI,TCGA.B6.A0RL,TCGA.B6.A0RM,TCGA.B6.A0RN,TCGA.B6.A0RO,TCGA.B6.A0RP,TCGA.B6.A0RQ,TCGA.B6.A0RS,TCGA.B6.A0RT,TCGA.B6.A0RU,TCGA.B6.A0RV,TCGA.B6.A0WS,TCGA.B6.A0WT,TCGA.B6.A0WV,TCGA.B6.A0WW,TCGA.B6.A0WX,TCGA.B6.A0WY,TCGA.B6.A0WZ,TCGA.B6.A0X0,TCGA.B6.A0X1,TCGA.B6.A0X4,TCGA.B6.A0X5,TCGA.B6.A0X7,TCGA.B6.A1KC,TCGA.B6.A1KF,TCGA.B6.A1KI,TCGA.B6.A1KN,TCGA.B6.A2IU,TCGA.B6.A3ZX,TCGA.B6.A400,TCGA.B6.A401,TCGA.B6.A402,TCGA.B6.A408,TCGA.B6.A409,TCGA.B6.A40B,TCGA.B6.A40C,TCGA.BH.A0AU,TCGA.BH.A0AV,TCGA.BH.A0AW,TCGA.BH.A0AY,TCGA.BH.A0AZ,TCGA.BH.A0B0,TCGA.BH.A0B1,TCGA.BH.A0B3,TCGA.BH.A0B4,TCGA.BH.A0B5,TCGA.BH.A0B7,TCGA.BH.A0B8,TCGA.BH.A0B9,TCGA.BH.A0BA,TCGA.BH.A0BC,TCGA.BH.A0BD,TCGA.BH.A0BF,TCGA.BH.A0BG,TCGA.BH.A0BJ,TCGA.BH.A0BL,TCGA.BH.A0BM,TCGA.BH.A0BO,TCGA.BH.A0BP,TCGA.BH.A0BQ,TCGA.BH.A0BR,TCGA.BH.A0BS,TCGA.BH.A0BT,TCGA.BH.A0BV,TCGA.BH.A0BW,TCGA.BH.A0BZ,TCGA.BH.A0C0,TCGA.BH.A0C1,TCGA.BH.A0C3,TCGA.BH.A0C7,TCGA.BH.A0DD,TCGA.BH.A0DE,TCGA.BH.A0DG,TCGA.BH.A0DH,TCGA.BH.A0DI,TCGA.BH.A0DK,TCGA.BH.A0DL,TCGA.BH.A0DP,TCGA.BH.A0DQ,TCGA.BH.A0DS,TCGA.BH.A0DT,TCGA.BH.A0DV,TCGA.BH.A0DX,TCGA.BH.A0DZ,TCGA.BH.A0E0,TCGA.BH.A0E1,TCGA.BH.A0E2,TCGA.BH.A0E6,TCGA.BH.A0E7,TCGA.BH.A0E9,TCGA.BH.A0EB,TCGA.BH.A0EE,TCGA.BH.A0EI,TCGA.BH.A0GY,TCGA.BH.A0GZ,TCGA.BH.A0H0,TCGA.BH.A0H3,TCGA.BH.A0H5,TCGA.BH.A0H6,TCGA.BH.A0H7,TCGA.BH.A0H9,TCGA.BH.A0HA,TCGA.BH.A0HB,TCGA.BH.A0HF,TCGA.BH.A0HI,TCGA.BH.A0HK,TCGA.BH.A0HL,TCGA.BH.A0HN,TCGA.BH.A0HO,TCGA.BH.A0HP,TCGA.BH.A0HQ,TCGA.BH.A0HU,TCGA.BH.A0HW,TCGA.BH.A0HX,TCGA.BH.A0HY,TCGA.BH.A0RX,TCGA.BH.A0W3,TCGA.BH.A0W4,TCGA.BH.A0W5,TCGA.BH.A0W7,TCGA.BH.A0WA,TCGA.BH.A18F,TCGA.BH.A18G,TCGA.BH.A18I,TCGA.BH.A18J,TCGA.BH.A18K,TCGA.BH.A18L,TCGA.BH.A18M,TCGA.BH.A18N,TCGA.BH.A18P,TCGA.BH.A18Q,TCGA.BH.A18R,TCGA.BH.A18S,TCGA.BH.A18T,TCGA.BH.A18U,TCGA.BH.A18V,TCGA.BH.A1EN,TCGA.BH.A1EO,TCGA.BH.A1ES,TCGA.BH.A1ET,TCGA.BH.A1EU,TCGA.BH.A1EV,TCGA.BH.A1EW,TCGA.BH.A1EX,TCGA.BH.A1EY,TCGA.BH.A1F0,TCGA.BH.A1F2,TCGA.BH.A1F6,TCGA.BH.A1F8,TCGA.BH.A1FB,TCGA.BH.A1FC,TCGA.BH.A1FD,TCGA.BH.A1FE,TCGA.BH.A1FG,TCGA.BH.A1FH,TCGA.BH.A1FJ,TCGA.BH.A1FL,TCGA.BH.A1FM,TCGA.BH.A1FN,TCGA.BH.A1FR,TCGA.BH.A1FU,TCGA.BH.A201,TCGA.BH.A202,TCGA.BH.A203,TCGA.BH.A204,TCGA.BH.A208,TCGA.BH.A209,TCGA.BH.A28O,TCGA.BH.A28Q,TCGA.BH.A2L8,TCGA.BH.A42T,TCGA.BH.A42U,TCGA.BH.A42V,TCGA.BH.A5IZ,TCGA.BH.A5J0,TCGA.BH.A6R8,TCGA.BH.A6R9,TCGA.BH.A8FZ,TCGA.BH.A8G0,TCGA.BH.AB28,TCGA.C8.A12K,TCGA.C8.A12L,TCGA.C8.A12M,TCGA.C8.A12N,TCGA.C8.A12O,TCGA.C8.A12P,TCGA.C8.A12Q,TCGA.C8.A12T,TCGA.C8.A12U,TCGA.C8.A12V,TCGA.C8.A12W,TCGA.C8.A12X,TCGA.C8.A12Y,TCGA.C8.A12Z,TCGA.C8.A130,TCGA.C8.A131,TCGA.C8.A132,TCGA.C8.A133,TCGA.C8.A134,TCGA.C8.A135,TCGA.C8.A137,TCGA.C8.A138,TCGA.C8.A1HE,TCGA.C8.A1HF,TCGA.C8.A1HG,TCGA.C8.A1HI,TCGA.C8.A1HJ,TCGA.C8.A1HK,TCGA.C8.A1HM,TCGA.C8.A1HN,TCGA.C8.A1HO,TCGA.C8.A26V,TCGA.C8.A26W,TCGA.C8.A26X,TCGA.C8.A26Y,TCGA.C8.A26Z,TCGA.C8.A273,TCGA.C8.A274,TCGA.C8.A275,TCGA.C8.A278,TCGA.C8.A27A,TCGA.C8.A27B,TCGA.C8.A3M7,TCGA.C8.A3M8,TCGA.C8.A8HP,TCGA.C8.A8HQ,TCGA.C8.A8HR,TCGA.C8.A9FZ,TCGA.D8.A13Y,TCGA.D8.A13Z,TCGA.D8.A140,TCGA.D8.A141,TCGA.D8.A142,TCGA.D8.A143,TCGA.D8.A145,TCGA.D8.A147,TCGA.D8.A1J8,TCGA.D8.A1J9,TCGA.D8.A1JA,TCGA.D8.A1JB,TCGA.D8.A1JC,TCGA.D8.A1JD,TCGA.D8.A1JE,TCGA.D8.A1JF,TCGA.D8.A1JG,TCGA.D8.A1JH,TCGA.D8.A1JI,TCGA.D8.A1JJ,TCGA.D8.A1JK,TCGA.D8.A1JL,TCGA.D8.A1JM,TCGA.D8.A1JN,TCGA.D8.A1JP,TCGA.D8.A1JS,TCGA.D8.A1JT,TCGA.D8.A1JU,TCGA.D8.A1X5,TCGA.D8.A1X6,TCGA.D8.A1X7,TCGA.D8.A1X8,TCGA.D8.A1X9,TCGA.D8.A1XA,TCGA.D8.A1XB,TCGA.D8.A1XC,TCGA.D8.A1XD,TCGA.D8.A1XF,TCGA.D8.A1XG,TCGA.D8.A1XJ,TCGA.D8.A1XK,TCGA.D8.A1XL,TCGA.D8.A1XM,TCGA.D8.A1XO,TCGA.D8.A1XQ,TCGA.D8.A1XR,TCGA.D8.A1XS,TCGA.D8.A1XT,TCGA.D8.A1XU,TCGA.D8.A1XV,TCGA.D8.A1XW,TCGA.D8.A1XY,TCGA.D8.A1XZ,TCGA.D8.A1Y0,TCGA.D8.A1Y1,TCGA.D8.A1Y2,TCGA.D8.A1Y3,TCGA.D8.A27E,TCGA.D8.A27F,TCGA.D8.A27G,TCGA.D8.A27H,TCGA.D8.A27I,TCGA.D8.A27K,TCGA.D8.A27L,TCGA.D8.A27M,TCGA.D8.A27N,TCGA.D8.A27P,TCGA.D8.A27R,TCGA.D8.A27T,TCGA.D8.A27V,TCGA.D8.A27W,TCGA.D8.A3Z5,TCGA.D8.A3Z6,TCGA.D8.A4Z1,TCGA.D8.A73U,TCGA.D8.A73W,TCGA.D8.A73X,TCGA.E2.A105,TCGA.E2.A106,TCGA.E2.A107,TCGA.E2.A108,TCGA.E2.A109,TCGA.E2.A10A,TCGA.E2.A10B,TCGA.E2.A10C,TCGA.E2.A10E,TCGA.E2.A10F,TCGA.E2.A14N,TCGA.E2.A14O,TCGA.E2.A14P,TCGA.E2.A14Q,TCGA.E2.A14R,TCGA.E2.A14S,TCGA.E2.A14T,TCGA.E2.A14U,TCGA.E2.A14V,TCGA.E2.A14W,TCGA.E2.A14X,TCGA.E2.A14Y,TCGA.E2.A14Z,TCGA.E2.A150,TCGA.E2.A152,TCGA.E2.A153,TCGA.E2.A154,TCGA.E2.A155,TCGA.E2.A156,TCGA.E2.A159,TCGA.E2.A15A,TCGA.E2.A15C,TCGA.E2.A15D,TCGA.E2.A15E,TCGA.E2.A15F,TCGA.E2.A15G,TCGA.E2.A15H,TCGA.E2.A15I,TCGA.E2.A15J,TCGA.E2.A15K,TCGA.E2.A15L,TCGA.E2.A15M,TCGA.E2.A15P,TCGA.E2.A15R,TCGA.E2.A15S,TCGA.E2.A15T,TCGA.E2.A1AZ,TCGA.E2.A1B0,TCGA.E2.A1B1,TCGA.E2.A1B4,TCGA.E2.A1B5,TCGA.E2.A1B6,TCGA.E2.A1BD,TCGA.E2.A1IE,TCGA.E2.A1IF,TCGA.E2.A1IG,TCGA.E2.A1IH,TCGA.E2.A1II,TCGA.E2.A1IJ,TCGA.E2.A1IK,TCGA.E2.A1IL,TCGA.E2.A1IN,TCGA.E2.A1IO,TCGA.E2.A1IU,TCGA.E2.A1L6,TCGA.E2.A1L7,TCGA.E2.A1L9,TCGA.E2.A1LA,TCGA.E2.A1LB,TCGA.E2.A1LE,TCGA.E2.A1LH,TCGA.E2.A1LI,TCGA.E2.A1LK,TCGA.E2.A1LL,TCGA.E2.A1LS,TCGA.E2.A2P6,TCGA.E2.A3DX,TCGA.E2.A56Z,TCGA.E2.A570,TCGA.E2.A573,TCGA.E2.A574,TCGA.E2.A576,TCGA.E2.A9RU,TCGA.E9.A1N3,TCGA.E9.A1N4,TCGA.E9.A1N5,TCGA.E9.A1N6,TCGA.E9.A1N8,TCGA.E9.A1N9,TCGA.E9.A1NA,TCGA.E9.A1NC,TCGA.E9.A1ND,TCGA.E9.A1NE,TCGA.E9.A1NF,TCGA.E9.A1NG,TCGA.E9.A1NH,TCGA.E9.A1NI,TCGA.E9.A1QZ,TCGA.E9.A1R0,TCGA.E9.A1R2,TCGA.E9.A1R3,TCGA.E9.A1R4,TCGA.E9.A1R5,TCGA.E9.A1R6,TCGA.E9.A1R7,TCGA.E9.A1RA,TCGA.E9.A1RB,TCGA.E9.A1RC,TCGA.E9.A1RD,TCGA.E9.A1RE,TCGA.E9.A1RF,TCGA.E9.A1RG,TCGA.E9.A1RH,TCGA.E9.A1RI,TCGA.E9.A226,TCGA.E9.A227,TCGA.E9.A228,TCGA.E9.A229,TCGA.E9.A22A,TCGA.E9.A22B,TCGA.E9.A22D,TCGA.E9.A22E,TCGA.E9.A22G,TCGA.E9.A22H,TCGA.E9.A243,TCGA.E9.A244,TCGA.E9.A245,TCGA.E9.A247,TCGA.E9.A248,TCGA.E9.A249,TCGA.E9.A24A,TCGA.E9.A295,TCGA.E9.A2JS,TCGA.E9.A2JT,TCGA.E9.A3HO,TCGA.E9.A3Q9,TCGA.E9.A3QA,TCGA.E9.A3X8,TCGA.E9.A54X,TCGA.E9.A54Y,TCGA.E9.A5FK,TCGA.E9.A5FL,TCGA.E9.A5UO,TCGA.E9.A5UP,TCGA.E9.A6HE,TCGA.EW.A1IW,TCGA.EW.A1IX,TCGA.EW.A1IY,TCGA.EW.A1IZ,TCGA.EW.A1J1,TCGA.EW.A1J2,TCGA.EW.A1J3,TCGA.EW.A1J6,TCGA.EW.A1OV,TCGA.EW.A1OW,TCGA.EW.A1OX,TCGA.EW.A1OY,TCGA.EW.A1OZ,TCGA.EW.A1P0,TCGA.EW.A1P1,TCGA.EW.A1P4,TCGA.EW.A1P5,TCGA.EW.A1P6,TCGA.EW.A1P7,TCGA.EW.A1P8,TCGA.EW.A1PA,TCGA.EW.A1PB,TCGA.EW.A1PC,TCGA.EW.A1PD,TCGA.EW.A1PE,TCGA.EW.A1PF,TCGA.EW.A1PG,TCGA.EW.A1PH,TCGA.EW.A2FR,TCGA.EW.A2FS,TCGA.EW.A2FV,TCGA.EW.A2FW,TCGA.EW.A3E8,TCGA.EW.A3U0,TCGA.EW.A423,TCGA.EW.A424,TCGA.EW.A6S9,TCGA.EW.A6SA,TCGA.EW.A6SB,TCGA.EW.A6SC,TCGA.EW.A6SD,TCGA.GI.A2C8,TCGA.GI.A2C9,TCGA.GM.A2D9,TCGA.GM.A2DA,TCGA.GM.A2DB,TCGA.GM.A2DC,TCGA.GM.A2DF,TCGA.GM.A2DH,TCGA.GM.A2DI,TCGA.GM.A2DK,TCGA.GM.A2DL,TCGA.GM.A2DM,TCGA.GM.A2DN,TCGA.GM.A3NW,TCGA.GM.A3NY,TCGA.GM.A3XG,TCGA.GM.A3XL,TCGA.GM.A3XN,TCGA.GM.A4E0,TCGA.GM.A5PV,TCGA.GM.A5PX,TCGA.HN.A2NL,TCGA.HN.A2OB,TCGA.JL.A3YW,TCGA.JL.A3YX,TCGA.LD.A66U,TCGA.LD.A7W5,TCGA.LD.A7W6,TCGA.LD.A9QF,TCGA.LL.A441,TCGA.LL.A5YL,TCGA.LL.A5YM,TCGA.LL.A5YN,TCGA.LL.A5YO,TCGA.LL.A6FP,TCGA.LL.A6FQ,TCGA.LL.A6FR,TCGA.LL.A73Y,TCGA.LL.A73Z,TCGA.LL.A7SZ,TCGA.LL.A7T0,TCGA.LL.A8F5,TCGA.LL.A9Q3,TCGA.LQ.A4E4,TCGA.MS.A51U,TCGA.OK.A5Q2,TCGA.OL.A5D6,TCGA.OL.A5D7,TCGA.OL.A5D8,TCGA.OL.A5DA,TCGA.OL.A5RV,TCGA.OL.A5RW,TCGA.OL.A5RX,TCGA.OL.A5RY,TCGA.OL.A5RZ,TCGA.OL.A5S0,TCGA.OL.A66H,TCGA.OL.A66I,TCGA.OL.A66J,TCGA.OL.A66K,TCGA.OL.A66L,TCGA.OL.A66N,TCGA.OL.A66O,TCGA.OL.A66P,TCGA.OL.A6VO,TCGA.OL.A6VQ,TCGA.OL.A6VR,TCGA.OL.A97C,TCGA.PE.A5DC,TCGA.PE.A5DD,TCGA.PE.A5DE,TCGA.PL.A8LV,TCGA.PL.A8LX,TCGA.PL.A8LY,TCGA.PL.A8LZ,TCGA.S3.A6ZF,TCGA.S3.A6ZG,TCGA.S3.A6ZH,TCGA.S3.AA0Z,TCGA.S3.AA10,TCGA.S3.AA11,TCGA.S3.AA14,TCGA.S3.AA15,TCGA.UL.AAZ6,TCGA.UU.A93S,TCGA.V7.A7HQ,TCGA.WT.AB44,TCGA.XX.A899,TCGA.XX.A89A,TCGA.Z7.A8R6
0,years_to_birth,42,63,40,39,53,62,71,44,66,79,71,55,72,65,53,63,50,48,74,80,81,81,59,71,61,61,69,73,84,68,65,90,88,74,72,56,78,70,51,51,55,52,50,70,49,62,46,47,78,72,63,62,87,NaN,57,43,89,63,52,50,78,72,59,48,53,54,79,61,56,84,49,61,63,82,64,66,NaN,61,55,50,62,52,50,52,70,59,56,54,61,39,52,39,54,77,50,67,45,66,36,48,36,62,47,50,34,60,37,40,85,60,54,73,71,73,41,67,52,63,46,60,76,45,42,37,73,70,54,56,64,63,52,58,79,80,53,46,62,62,66,63,82,48,62,59,55,66,37,62,39,50,51,59,63,48,67,63,53,62,39,61,48,67,56,74,62,61,63,49,85,50,70,39,50,90,34,66,55,47,62,45,35,46,42,49,49,46,57,49,67,46,77,66,62,59,57,78,79,57,37,62,56,63,46,62,44,61,50,49,71,62,62,79,70,40,56,62,52,54,54,84,62,47,51,48,68,48,66,60,63,63,69,77,66,84,42,66,69,69,57,65,65,69,35,58,51,68,80,73,66,76,85,80,58,67,44,59,89,52,65,41,66,53,52,89,45,70,52,64,42,76,74,48,75,45,73,65,76,40,58,47,79,75,57,83,82,68,51,70,62,83,84,66,73,64,57,80,54,83,62,50,76,90,84,78,41,65,62,NaN,79,45,87,65,58,76,48,46,79,87,68,79,53,50,75,66,74,66,63,76,74,58,79,47,73,49,43,51,56,72,72,75,71,74,66,29,68,62,36,51,58,79,76,41,56,55,70,62,71,32,59,88,62,61,55,63,58,67,52,55,45,56,61,68,59,69,55,63,54,54,67,36,34,29,59,69,54,57,42,31,41,41,67,41,48,61,71,61,61,36,50,64,59,53,68,49,54,59,40,38,72,39,61,29,47,63,42,43,51,36,75,69,46,77,84,51,69,61,45,48,84,49,43,27,68,46,53,35,66,50,64,54,43,73,36,47,59,54,51,47,83,70,60,46,47,80,49,54,62,39,68,65,64,65,65,46,26,38,54,43,47,49,45,61,46,47,52,55,52,57,58,51,50,50,62,45,69,55,40,62,49,65,46,59,68,54,68,73,45,49,49,62,51,64,90,38,50,81,42,63,75,45,66,74,40,61,26,51,44,60,57,60,71,73,68,38,39,40,42,58,61,67,58,40,40,50,54,48,62,61,62,67,68,63,57,62,50,43,47,47,55,44,76,51,45,52,56,62,47,56,66,53,65,40,42,64,44,51,60,47,56,73,41,35,54,54,76,39,59,55,56,78,71,59,62,61,47,48,58,62,30,63,63,49,64,60,42,71,41,54,62,43,38,52,49,69,79,53,69,68,51,67,62,69,46,45,82,65,69,31,55,77,78,81,56,67,48,65,56,52,62,54,60,59,58,46,77,49,82,50,81,53,56,46,50,39,88,60,56,50,79,70,72,48,78,68,35,55,83,45,38,67,79,80,53,51,89,60,78,68,31,88,47,66,69,44,34,73,44,64,60,78,80,48,77,50,46,45,75,80,41,51,63,46,61,58,54,53,80,67,70,58,50,55,78,NaN,46,55,49,62,NaN,45,52,82,56,65,52,64,34,54,NaN,NaN,NaN,NaN,53,NaN,74,56,34,47,58,58,90,NaN,NaN,63,56,61,48,48,60,68,59,53,49,49,52,51,62,40,74,51,80,45,77,48,60,54,59,41,62,79,62,56,54,54,90,72,59,80,73,77,70,51,81,80,40,62,66,64,62,85,36,45,86,76,55,34,57,56,69,56,48,61,56,84,53,74,81,65,80,71,61,66,40,75,72,58,47,49,59,36,64,41,53,62,55,54,56,68,88,79,53,79,34,54,64,64,41,67,54,64,47,37,76,79,50,62,65,52,74,53,78,55,35,64,48,56,51,68,58,61,50,45,61,47,40,64,76,38,44,51,58,65,66,61,64,34,65,63,50,45,74,46,44,53,61,74,45,80,51,57,71,78,60,37,60,44,40,40,59,41,71,59,57,84,74,46,77,43,69,47,48,44,69,90,70,41,45,52,48,58,58,61,75,28,60,62,71,51,61,58,51,70,66,63,63,64,48,40,56,67,74,68,62,63,43,45,42,58,37,74,71,38,56,47,42,52,54,47,59,51,45,69,71,72,63,49,78,33,48,85,63,60,65,41,63,45,80,48,38,53,38,50,61,70,56,58,43,63,56,55,68,43,77,64,59,58,59,70,66,61,56,50,53,52,59,41,39,52,60,61,75,51,34,59,62,60,32,63,58,69,46,62,57,53,58,52,58,50,57,58,63,72,46,49,44,67,63,65,56,45,NaN,NaN,44,52,54,73,62,64,88,46,50,90,77,50,67,55,49,70,61,69,73,44,59,71,70,40,61,43,40,51,52,57,66,74,36,80,72,71,59,39,75,43,49,48,67,72,64,41,54,35,30,29,64,71,29,63,65,67,47,51,73,63,75,NaN,46,68,46

Column names:
['attrib_name', 'TCGA.5L.AAT0', 'TCGA.5L.AAT1', 'TCGA.A1.A0SP', 'TCGA.A2.A04V', 'TCGA.A2.A04Y', 'TCGA.A2.A0CQ', 'TCGA.A2.A1G4', 'TCGA.A2.A25A', 'TCGA.A7.A0CD']


======================================================================
DATASET SUMMARY
======================================================================
Clinical variables (rows): 20
Patients (columns):        1097

Feature column:
attrib_name

Example patient IDs:
['TCGA.5L.AAT0', 'TCGA.5L.AAT1', 'TCGA.A1.A0SP', 'TCGA.A2.A04V', 'TCGA.A2.A04Y', 'TCGA.A2.A0CQ', 'TCGA.A2.A1G4', 'TCGA.A2.A25A', 'TCGA.A7.A0CD', 'TCGA.A7.A13G']

Missing values:
4144

Duplicate clinical variables:
0

Duplicate patient columns:
0

##Convert Patient IDs

In [11]:
# ============================================================
# Convert Patient IDs
# ============================================================

new_columns = [clinical_raw.columns[0]]

for col in clinical_raw.columns[1:]:
    new_columns.append(col.replace(".", "-"))

clinical_raw.columns = new_columns

print("="*70)
print("PATIENT ID CONVERSION")
print("="*70)

print("Example IDs:")

print(clinical_raw.columns[1:11].tolist())

======================================================================
PATIENT ID CONVERSION
======================================================================
Example IDs:
['TCGA-5L-AAT0', 'TCGA-5L-AAT1', 'TCGA-A1-A0SP', 'TCGA-A2-A04V', 'TCGA-A2-A04Y', 'TCGA-A2-A0CQ', 'TCGA-A2-A1G4', 'TCGA-A2-A25A', 'TCGA-A7-A0CD', 'TCGA-A7-A13G']

##Transpose Dataset

In [12]:
# ============================================================
# Transpose Clinical Dataset
# ============================================================

clinical_df = clinical_raw.set_index(
    clinical_raw.columns[0]
).T

clinical_df.index.name = "patient_id"

clinical_df = clinical_df.reset_index()

print("="*70)
print("PATIENT-LEVEL CLINICAL MATRIX")
print("="*70)

print(f"Patients : {clinical_df.shape[0]}")
print(f"Variables: {clinical_df.shape[1]-1}")

print("\nFirst rows:")

display(clinical_df.head())

======================================================================
PATIENT-LEVEL CLINICAL MATRIX
======================================================================
Patients : 1097
Variables: 20

First rows:

attrib_name,patient_id,years_to_birth,Tumor_purity,pathologic_stage,pathology_T_stage,pathology_N_stage,pathology_M_stage,histological_type,number_of_lymph_nodes,PAM50,ER.Status,PR.Status,HER2.Status,gender,radiation_therapy,race,ethnicity,Median_overall_survival,overall_survival,status,overallsurvival
0,TCGA-5L-AAT0,42,0.6501,stageii,t2,n0,m0,infiltratinglobularcarcinoma,0,NaN,NaN,NaN,NaN,female,yes,white,hispanicorlatino,0,1477,0,"1477,0"
1,TCGA-5L-AAT1,63,0.5553,stageiv,t2,n0,m1,infiltratinglobularcarcinoma,0,NaN,NaN,NaN,NaN,female,no,white,hispanicorlatino,0,1471,0,"1471,0"
2,TCGA-A1-A0SP,40,0.6913,stageii,t2,n0,m0,infiltratingductalcarcinoma,0,Basal,NaN,NaN,NaN,female,NaN,NaN,nothispanicorlatino,0,584,0,"584,0"
3,TCGA-A2-A04V,39,0.8341,stageii,t2,n0,m0,infiltratingductalcarcinoma,0,LumA,NaN,NaN,NaN,female,no,white,nothispanicorlatino,0,1920,1,"1920,1"
4,TCGA-A2-A04Y,53,0.7318,stageii,t2,n1,m0,infiltratingductalcarcinoma,1,LumB,NaN,NaN,NaN,female,yes,white,NaN,0,1099,0,"1099,0"

##Clinical Variable Selection

In [13]:
# ============================================================
# Clinical Variable Selection
# ============================================================

clinical = clinical_df.copy()

# Keep only medically meaningful variables
selected_columns = [
    "patient_id",
    "years_to_birth",
    "Tumor_purity",
    "pathologic_stage",
    "pathology_T_stage",
    "pathology_N_stage",
    "pathology_M_stage",
    "histological_type",
    "number_of_lymph_nodes",
    "PAM50",
    "radiation_therapy",
    "race",
    "ethnicity"
]

clinical = clinical[selected_columns]

print("="*70)
print("CLINICAL FEATURE SELECTION")
print("="*70)

print("Selected variables:")
for col in clinical.columns:
    print("-", col)

print("\nFinal shape:", clinical.shape)

======================================================================
CLINICAL FEATURE SELECTION
======================================================================
Selected variables:
- patient_id
- years_to_birth
- Tumor_purity
- pathologic_stage
- pathology_T_stage
- pathology_N_stage
- pathology_M_stage
- histological_type
- number_of_lymph_nodes
- PAM50
- radiation_therapy
- race
- ethnicity

Final shape: (1097, 13)

##Missing Value Processing

In [14]:
# ============================================================
# Missing Value Processing
# ============================================================

import numpy as np
from sklearn.impute import SimpleImputer

clinical_processed = clinical.copy()

# Replace common TCGA missing values
clinical_processed = clinical_processed.replace(
    ["NA", "na", "NaN", "NAN", "[Not Available]", "[Not Applicable]", ""],
    np.nan
)

# Numeric columns
numeric_cols = [
    "years_to_birth",
    "Tumor_purity",
    "number_of_lymph_nodes"
]

# Categorical columns
categorical_cols = [
    c for c in clinical_processed.columns
    if c not in numeric_cols + ["patient_id"]
]

# Median imputation
median_imputer = SimpleImputer(strategy="median")

clinical_processed[numeric_cols] = median_imputer.fit_transform(
    clinical_processed[numeric_cols]
)

# Most frequent imputation
mode_imputer = SimpleImputer(strategy="most_frequent")

clinical_processed[categorical_cols] = mode_imputer.fit_transform(
    clinical_processed[categorical_cols]
)

print("="*70)
print("MISSING VALUE PROCESSING")
print("="*70)

print(clinical_processed.isna().sum())

======================================================================
MISSING VALUE PROCESSING
======================================================================
attrib_name
patient_id               0
years_to_birth           0
Tumor_purity             0
pathologic_stage         0
pathology_T_stage        0
pathology_N_stage        0
pathology_M_stage        0
histological_type        0
number_of_lymph_nodes    0
PAM50                    0
radiation_therapy        0
race                     0
ethnicity                0
dtype: int64

##Clinical Encoding

In [15]:
# ============================================================
# Clinical Encoding
# ============================================================

from sklearn.preprocessing import OrdinalEncoder

encoded = clinical_processed.copy()

# -------------------------
# Stage Mapping
# -------------------------

stage_map = {
    "stagei":1,
    "stageia":1,
    "stageib":1,

    "stageii":2,
    "stageiia":2,
    "stageiib":2,

    "stageiii":3,
    "stageiiia":3,
    "stageiiib":3,
    "stageiiic":3,

    "stageiv":4
}

encoded["pathologic_stage"] = (
    encoded["pathologic_stage"]
    .str.lower()
    .str.replace(" ","")
    .map(stage_map)
)

# -------------------------
# T Stage
# -------------------------

t_map = {
    "tx":0,
    "t0":0,
    "tis":0,
    "t1":1,
    "t1a":1,
    "t1b":1,
    "t1c":1,
    "t2":2,
    "t3":3,
    "t4":4,
    "t4a":4,
    "t4b":4,
    "t4c":4,
    "t4d":4
}

encoded["pathology_T_stage"] = (
    encoded["pathology_T_stage"]
    .str.lower()
    .str.replace(" ","")
    .map(t_map)
)

# -------------------------
# N Stage
# -------------------------

n_map = {
    "nx":0,
    "n0":0,
    "n1":1,
    "n1a":1,
    "n1b":1,
    "n1c":1,
    "n2":2,
    "n2a":2,
    "n2b":2,
    "n3":3,
    "n3a":3,
    "n3b":3,
    "n3c":3
}

encoded["pathology_N_stage"] = (
    encoded["pathology_N_stage"]
    .str.lower()
    .str.replace(" ","")
    .map(n_map)
)

# -------------------------
# M Stage
# -------------------------

m_map = {
    "mx":0,
    "m0":0,
    "m1":1
}

encoded["pathology_M_stage"] = (
    encoded["pathology_M_stage"]
    .str.lower()
    .str.replace(" ","")
    .map(m_map)
)

# -------------------------
# Binary
# -------------------------

binary_map = {
    "yes":1,
    "no":0
}

encoded["radiation_therapy"] = (
    encoded["radiation_therapy"]
    .str.lower()
    .map(binary_map)
)

# -------------------------
# One-Hot Encoding
# -------------------------

one_hot_cols = [
    "histological_type",
    "PAM50",
    "race",
    "ethnicity"
]

encoded = pd.get_dummies(
    encoded,
    columns=one_hot_cols,
    drop_first=True
)

print("="*70)
print("ENCODING FINISHED")
print("="*70)

print("Final shape:", encoded.shape)

======================================================================
ENCODING FINISHED
======================================================================
Final shape: (1097, 21)

##Scaling

In [16]:
# ============================================================
# Standardization
# ============================================================

from sklearn.preprocessing import StandardScaler

scaled = encoded.copy()

numeric_cols = [
    "years_to_birth",
    "Tumor_purity",
    "number_of_lymph_nodes"
]

scaler = StandardScaler()

scaled[numeric_cols] = scaler.fit_transform(
    scaled[numeric_cols]
)

print("="*70)
print("STANDARDIZATION")
print("="*70)

print(scaled[numeric_cols].describe())

======================================================================
STANDARDIZATION
======================================================================
       years_to_birth  Tumor_purity  number_of_lymph_nodes
count    1.097000e+03  1.097000e+03           1.097000e+03
mean     1.943143e-17  9.391859e-17          -2.914715e-17
std      1.000456e+00  1.000456e+00           1.000456e+00
min     -2.489186e+00 -4.399177e+00          -5.020904e-01
25%     -7.331001e-01 -5.304350e-01          -5.020904e-01
50%      3.041534e-02  1.302624e-01          -2.689997e-01
75%      6.412277e-01  7.088349e-01          -3.590913e-02
max      2.397313e+00  2.005074e+00           7.656081e+00

##Quality Control & Save

In [17]:
# ============================================================
# Quality Control
# ============================================================

print("="*70)
print("CLINICAL QUALITY CONTROL")
print("="*70)

print("Patients:", scaled.patient_id.nunique())

print("Features:", scaled.shape[1]-1)

print("Missing values:",
      scaled.isna().sum().sum())

print("Infinite values:",
      np.isinf(
          scaled.select_dtypes(include=np.number)
      ).sum().sum())

print("Duplicate patients:",
      scaled.patient_id.duplicated().sum())

print("\nFirst rows:")
display(scaled.head())

# ============================================================
# Save Files
# ============================================================

OUTPUT_FOLDER = "/content/drive/MyDrive/TCGA_BRCA_Project/Clinical"

os.makedirs(OUTPUT_FOLDER, exist_ok=True)

scaled.to_csv(
    f"{OUTPUT_FOLDER}/clinical_processed.csv",
    index=False
)

statistics = scaled.describe(include="all")

statistics.to_csv(
    f"{OUTPUT_FOLDER}/clinical_statistics.csv"
)

with open(
    f"{OUTPUT_FOLDER}/preprocessing_report.txt",
    "w"
) as f:

    f.write("Clinical preprocessing completed successfully.\n\n")

    f.write(f"Patients: {scaled.shape[0]}\n")
    f.write(f"Features: {scaled.shape[1]-1}\n")
    f.write(f"Missing values: {scaled.isna().sum().sum()}\n")
    f.write(f"Duplicate patients: {scaled.patient_id.duplicated().sum()}\n")

print("="*70)
print("FILES SAVED SUCCESSFULLY")
print("="*70)

print(os.listdir(OUTPUT_FOLDER))

======================================================================
CLINICAL QUALITY CONTROL
======================================================================
Patients: 1097
Features: 20
Missing values: 0
Infinite values: 0
Duplicate patients: 0

First rows:

,patient_id,years_to_birth,Tumor_purity,pathologic_stage,pathology_T_stage,pathology_N_stage,pathology_M_stage,number_of_lymph_nodes,radiation_therapy,histological_type_infiltratinglobularcarcinoma,histological_type_medullarycarcinoma,histological_type_metaplasticcarcinoma,histological_type_mixedhistology(pleasespecify),histological_type_mucinouscarcinoma,"histological_type_other,specify",PAM50_Her2,PAM50_LumA,PAM50_LumB,race_blackorafricanamerican,race_white,ethnicity_nothispanicorlatino
0,TCGA-5L-AAT0,-1.267561,-0.583705,2,2,0,0,-0.50209,1,True,False,False,False,False,False,False,True,False,False,True,False
1,TCGA-5L-AAT1,0.335822,-1.285095,4,2,0,1,-0.50209,0,True,False,False,False,False,False,False,True,False,False,True,False
2,TCGA-A1-A0SP,-1.420264,-0.278882,2,2,0,0,-0.50209,1,False,False,False,False,False,False,False,False,False,False,True,True
3,TCGA-A2-A04V,-1.496616,0.777642,2,2,0,0,-0.50209,0,False,False,False,False,False,False,False,True,False,False,True,True
4,TCGA-A2-A04Y,-0.427694,0.020763,2,2,1,0,-0.26900,1,False,False,False,False,False,False,False,False,True,False,True,True

======================================================================
FILES SAVED SUCCESSFULLY
======================================================================
['clinical_processed.csv', 'clinical_statistics.csv', 'preprocessing_report.txt']